spring:
  application:
    name: rest-unit-test
  datasource:
    url: jdbc:postgresql://localhost:5432/cardealers
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

server:
  port: 8099


app:
  environment:
    name: Development
    release: 1.0.0
    baseUrl: http://localhost:8080