

### GET request to example server
# < SQL
    # The default dataSource is the Spring JDBC Primary dataSource
    ### DataSource = default
    ### Query = "SELECT id, name, address FROM car_dealer"
# SQL

< {%
    markdowner.heading(3, "Before: TABLE: CARDEALERS");
    const columns = client.global.get("ResultSetColumns");
    const data = client.global.get("ResultSet");
    markdowner.table(columns, data);
%}

GET {{baseUrl}}/api/cardealer
Accept:  application/json


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response includes more than 1 car dealer", function () {
        const carDealers = jsonPath(response.body, "$");
        client.assert(carDealers.length > 0, "No car dealers");
    });

    client.test("SQL query returned results", function () {
        const resultSet = client.global.get("ResultSet");
        client.assert(resultSet.length > 0, "SQL returned no car dealers");
    });

    client.test("Response Data Matches Database", function () {
        const resultSet = client.global.get("ResultSet");
        const carDealers = jsonPath(response.body, "$");
        client.assert(carDealers.length === resultSet.length, "Car Dealers returned are not the same number of records in the database");
    });

    markdowner.heading(3, "Response Message");
    markdowner.codeBlock("json", JSON.stringify(JSON.parse(response.body), null, 2));

%}

###