

### GET request to example server
< {%
    markdowner.heading(3, "Before: TABLE: CARDEALERS");
    const result = client.sqlQuery("SELECT id, name, address FROM car_dealer");
    markdowner.table(result.columns, result.data);
    client.global.set("ResultSet", result.data);
%}

GET {{baseUrl}}/api/cardealer
Accept:  application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response includes more than 1 car dealer", function () {
        const carDealers = jsonPath(response.body, "$");
        client.assert(carDealers.length > 0, "No car dealers");
    });

    client.test("SQL query returned results", function () {
        const resultSet = client.global.get("ResultSet");
        client.assert(resultSet.length > 0, "SQL returned no car dealers");
    });

    client.test("Response Data Matches Database", function () {
        const resultSet = client.global.get("ResultSet");
        const carDealers = jsonPath(response.body, "$");
        client.assert(carDealers.length === resultSet.length, "Car Dealers returned are not the same number of records in the database");
    });

    markdowner.heading(3, "Response Message");
    markdowner.codeBlock("json", JSON.stringify(JSON.parse(response.body), null, 2));

%}

### Adding car to dealer
< {%
    markdowner.heading(3, "Before: TABLE: CAR");
    const result = client.sqlQuery("SELECT id, make, model, color, price FROM car WHERE dealer_id = 1");
    markdowner.table(result.columns, result.data);
%}
POST {{baseUrl}}/api/cardealer/1/car
Content-Type: application/json
Accept: application/json

{
  "make": "Chrysler",
  "model": "Valiant",
  "color": "Purple",
  "price": "4000"
}


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201");
    });

    client.test("Response includes ID", function () {
        const id = jsonPath(response.body, "$.id");
        client.assert(id, "Response did not contain ID")
    });

    markdowner.heading(3, "Response Message");
    markdowner.codeBlock("json", JSON.stringify(JSON.parse(response.body), null, 2));

    const id = jsonPath(response.body, "$.id");
    const query = "SELECT id, make, model, color, price FROM car WHERE car.id = " + id;
    const result = client.sqlQuery(query);
    client.assert(result.data.length === 1, "Record not found in DB: " + result.data.length);
    markdowner.heading(3, "After: TABLE: CAR");
    markdowner.table(result.columns, result.data);
    client.global.set("carId", id);
%}

### Get car
GET {{baseUrl}}/api/car/{{carId}}
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response includes ID", function () {
        const id = jsonPath(response.body, "$.id");
        client.assert(id, "Response did not contain ID")
    });

    markdowner.heading(3, "Response Message");
    markdowner.codeBlock("json", JSON.stringify(JSON.parse(response.body), null, 2));

%}
