### Get all car dealers
// Returns a list of all car dealers and their cars
GET http://localhost:8080/api/cardealer
Authorization: Basic {{username}} {{password}}
Accept: application/json

> {%
  // Basic assertions
  client.assert(response.status === 200, "Response status is 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected application/json content type");
%}